name: azure_common_lz_workflow

on:
  push:
    paths:
    - '.github/workflows/networkBp.yml'
  pull_request:
    paths:
    - '.github/workflows/networkBp.yml'

jobs:
   DeployNetwork:
      environment: Build
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Create Azure Blueprint
        uses: neilpeterson/action-create-blueprint@master
        env:
          AZURETENANTID: ${{ secrets.AZURETENANTID }}
          AZURECLIENTID: ${{ secrets.AZURECLIENTID }}
          AZUREPASSWORD: ${{ secrets.AZUREPASSWORD }}
        with:
          azureManagementGroupName: "8de3d3fb-4ae1-4c39-99e0-bede3ca0a96c"
          blueprintName: NetworkLzBpTest
          blueprintPath: network\blueprint.json