name: azure_common_lz_workflow

on:
  push:
    paths:
    - '.github/workflows/networkBp.yml'
  pull_request:
    paths:
    - '.github/workflows/networkBp.yml'

jobs:
   DeployNetwork:
      environment: Build
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build - Log in to Azure Powershell
        run: |
            Install-Module -Name Az.Blueprint -Verbose -Force
            Get-AzBlueprint
            Set-AzContext -Subscription "009bdc79-1eee-40cf-a62d-8dd277d1cd26"
            cd D:\a\az-blueprint-lz\az-blueprint-lz\network
            .\deploy.ps1