name: azure_common_lz_workflow

on:
  push:
    paths:
    - '.github/workflows/networkBp.yml'
  pull_request:
    paths:
    - '.github/workflows/networkBp.yml'

jobs:
   DeployNetwork:
      environment: Build
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Create Azure Blueprint
        uses: neilpeterson/action-create-blueprint@master
        env:
          AZURETENANTID: ${{ secrets.AZURETENANTID }}
          AZURECLIENTID: ${{ secrets.AZURECLIENTID }}
          AZUREPASSWORD: ${{ secrets.AZUREPASSWORD }}
        with:
          azureSubscriptionID: 009bdc79-1eee-40cf-a62d-8dd277d1cd26
          blueprintName: NetworkLzBpTest
          blueprintPath: D:\a\az-blueprint-lz\az-blueprint-lz\network\blueprint.json
      